# Generated by Django 3.1.6 on 2021-02-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20210210_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('uname', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('cpwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
    ]
