# Generated by Django 3.1.6 on 2021-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20210211_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_date',
            field=models.CharField(max_length=200),
        ),
    ]
