# Generated by Django 3.1.6 on 2021-02-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20210212_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetcat'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_date',
            field=models.DateField(),
        ),
    ]
